### ISSUE TITLE
Add possibility to compile libayatana-appindicator-rs bindings from a static file.

### ISSUE THREAD

**Issue by emirror-de** [emirror-de/openprobst#4]
**Repository**
To which repository does this feature belong to?
[libayatana-appindicator-rs](https://github.com/emirror-de/libayatana-appindicator-rs)

**Motivation**
What problem should this feature solve in the future? Please describe short and clear, but as detailed as possible.
Optionally remove the clang dependency.

**Desired solution**
How should the ideal solution look like? If possible, describe the algorithm that should be used.
A static file containing the generated bindings should be added to the crate. A feature should be added to make the user decide if this file should be used, or the bindings should be generated on build.

**Code examples**
Please provide a code example of how to use the desired feature. If possible provide an interface with one line comments how it should be used when finished.
In `Cargo.toml`:
```toml
libayatana-appindicator = { version = "XXX"} # for usage of bindings file
libayatana-appindicator = { version = "XXX", features = ["dynamic"] } # for dynamic generation
```

**Checklist**
- [X] Added a link to the repository
- [X] Checked the repository for already linked issues and provided links to them
- [X] Clear description of the motivation
- [X] Clear description of the desired solution
- [X] Code example is provided and commented
- [X] ***Added this issue to the openprobst.dev project***
